spring:
  datasource:
    url: jdbc:mysql://60.205.190.177:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456




mybatis:
  # 如果Mapper.java和Mapper.xml在同一个包下，可以不用设置
  mapperLocations: classpath:com.lc.mapper/*.xml
  typeAliasesPackage: com.lc.mapper
  configuration:
    cacheEnabled: false
    # 一定要设置，避免个别SQL执行时间过长，把系统搞跨
    default-statement-timeout: 5